[package]
name = "gorp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
matrix-sdk = { version = "0.7", features = ["e2e-encryption"] }
rusqlite = { version = "0.30", features = ["bundled"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
anyhow = "1.0"
uuid = { version = "1.6", features = ["v4"] }
futures-util = "0.3"
chrono = "0.4"
axum = "0.7"
tower = "0.5"
tower-http = { version = "0.6", features = ["trace"] }
directories = "6.0.0"
tracing-appender = "0.2.4"
pulldown-cmark = "0.10"
two_timer = "2.2"
cron = "0.15"
regex = "1.12.2"
chrono-tz = "0.10.4"
clap = { version = "4.5.53", features = ["derive"] }
